# fly.toml app configuration file generated for fancymc on 2024-06-26T21:39:40+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fancymc'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
